services:
  - type: web
    name: my-app-backend
    env: python
    root: backend          
    buildCommand: |
      cd ../frontend
      npm install
      npm run build
      cd ../backend
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
