services:
  - type: web
    name: my-app-backend
    env: python
    buildCommand: |
      cd frontend
      npm install
      npm run build
      cd ..
      pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
